apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: clone
spec:
  steps:
  - name: clone
    args:
      - >-
        git
        clone 
        -b main 
        --depth '1' 
        https://github.com/azgabur/kuadrant-helm-install 
        $(workspaces.shared-workspace.path)/kuadrant-helm-install
    command:
      - /bin/bash
      - -c
    computeResources:
      limits:
        cpu: 250m
        memory: 128Mi
    image: docker.io/s390x/alpine:3.18
    imagePullPolicy: IfNotPresent
  workspaces:
  - name: shared-workspace
